[package]
name = "iceoryx2-pal-concurrency-sync"
description = "iceoryx2: [internal] low-level basic building blocks to implement posix mutex, condition variables etc."
categories = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[features]
# Enables 64-bit applications to communicate with 32-bit applications at the cost of being no
# longer lock-free. Meaning, a crash at the wrong time can lead to a system deadlock.
enforce_32bit_rwlock_atomic = []

[dependencies]

[dev-dependencies]
iceoryx2-bb-testing = { workspace = true }
generic-tests = { workspace = true }
