[package]
name = "iox2"
description = "Iceoryx2: CLI entry-point"
categories = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
better-panic = { workspace = true }
colored = { workspace = true }
clap = { workspace = true }
human-panic = { workspace = true }
cargo_metadata = { workspace = true }

[dev-dependencies]
iceoryx2-bb-testing = { workspace = true }
tempfile = { workspace = true }
