[package]
name = "iceoryx2_pal_posix"
description = "Iceoryx2: A posix layer that ensures uniform posix behavior on all platforms according to https://posix.opengroup.org"
categories = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[build-dependencies]
cc = { workspace = true }
bindgen = { workspace = true }

[dependencies]
iceoryx2_pal_concurrency_primitives = { workspace = true }
iceoryx2_pal_settings = { workspace = true }
lazy_static = { workspace = true }

[target.'cfg(windows)'.dependencies]
windows-sys = { workspace = true }

[dev-dependencies]
iceoryx2_bb_testing = { workspace = true }
