[package]
name = "iceoryx2-cli-utils"
description = "Common helpers for iceoryx2 CLI tools."
categories = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iceoryx2 = { workspace = true }

anyhow = { workspace = true }
clap = { workspace = true }
colored = { workspace = true }
toml = { workspace = true }
serde = { workspace = true }
serde_yaml = { workspace = true }
serde_json = { workspace = true }
ron = { workspace = true }
