[package]
name = "iceoryx2-ffi"
categories.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/lib.rs"
crate-type = ["rlib", "cdylib", "staticlib"] # without "rlib" the doc examples are not run

[build-dependencies]
cbindgen = { workspace = true }

[dependencies]
iceoryx2 = { workspace = true }
iceoryx2-bb-container = { workspace = true }
iceoryx2-bb-elementary = { workspace = true }
iceoryx2-bb-log = { workspace = true }

[dev-dependencies]
iceoryx2-bb-testing = { workspace = true }
