[package]
name = "iceoryx2_bb_lock_free"
description = "Iceoryx2: lock-free containers and constructs"
categories = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[dependencies]
iceoryx2_bb_log = { workspace = true }
iceoryx2_bb_elementary = { workspace = true }

tiny-fn = { workspace = true }

[dev-dependencies]
iceoryx2_bb_posix = { workspace = true }
iceoryx2_bb_memory = { workspace = true }
iceoryx2_bb_testing = { workspace = true }
pin-init = { workspace = true }
generic-tests = { workspace = true }
