[package]
name = "iceoryx2_pal_concurrency_primitives"
description = "Iceoryx2: low-level basic building blocks to implement posix mutex, condition variables etc."
categories = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[dependencies]

[dev-dependencies]
iceoryx2_bb_testing = { workspace = true }
